apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: loki-distributed
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/version: 2.9.6
    argocd.argoproj.io/instance: loki-distributed
    helm.sh/chart: loki-distributed-0.78.5
  name: loki-s3
  namespace: loki-distributed
  annotations:
    eks.amazonaws.com/role-arn: {your-role-arn}
