agent:
  tolerations: []
clickhouse:
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 20m
      memory: 128Mi
clusterId: tf-dev-eks-cluster-youngjin-01
commitHashKeyName: ""
custom-metrics:
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
global:
  groundcover_token: iOMTPdjSvIpPwM7u5RTWlX7Q0dGwLs5L
installationId: d79a68b5-bc20-4357-bf2b-c1525475b314
k8sWatcher:
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 10m
      memory: 256Mi
metrics-ingester:
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
opentelemetry-collector:
  resources:
    limits:
      cpu: 500m
      memory: 2048Mi
    requests:
      cpu: 50m
      memory: 256Mi
portal:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi
repositoryUrlKeyName: ""
storeIssuesLogsOnly: false
victoria-metrics-agent:
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 16m
      memory: 32Mi
victoria-metrics-single:
  server:
    resources:
      limits:
        cpu: 100m
        memory: 1024Mi
      requests:
        cpu: 20m
        memory: 128Mi
