apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-efs-pvc
  namespace: grafana
spec:
  storageClassName: dynamic-efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
