config:
  service: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

  inputs: |
    [INPUT]
        Name              tail
        Tag               kubelet.log
        Path              /var/log/message
        DB                /var/log/flb_kubelet.db
        Parser            syslog
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  outputs: |
    [OUTPUT]
        Name            newrelic
        Match           kubelet.log
        licenseKey      {your-licensekey}
        endpoint        https://log-api.newrelic.com/log/v1


