apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-server-pvc
  namespace: argocd
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
